Cosmetic changes
jmoeil/PHYS-F302 pull request #4
Opened 2021-10-04 23:04 UTC by Oedipsos

- Harmonize namings, labels, etc.
- Added space to new commands/environments.
- Added needed arguments for readability

2021-10-04 23:06 UTC, Oedipsos commented
Also added my name in authors and made a command for median point ;)

2021-10-05 07:28 UTC, jmoeil reviewed
I’ll try to see the difference between `\usepackage{braket} ` and the brakets in `\usepackage{physics}` so we can move forward with the best out of the two.

2021-10-05 07:28 UTC, jmoeil commented on notesdecours.tex
> +\usepackage{braket} % `physics' already implements braket notation, which one should we use?
I’ll try some things tonight to see the difference between the two.

2021-10-05 08:19 UTC, jmoeil requested changes
I tested a bit. There seems to be no graphical difference between `\bra`,`\ket` or `\braket` between the `physics` package or the `braket` package. I therefore propose to only use `physics` to lighten up the `notesdecours.tex` file as well as to stay consistant throughout the code.
I let you have the pleasure of removing line 15 from the code.

2021-10-05 08:39 UTC, jmoeil approved these changes

2021-10-05 08:39 UTC, merged